name: partslip
channels:
  - anaconda
  - conda-forge
  - defaults
  - iopath
  - pytorch
dependencies:
  - boost=1.73.0
  - eigen=3.4.0
  - fvcore=0.1.5.post20221221
  - iopath=0.1.9
  - jupyter=1.0.0
  - matplotlib=3.7.1
  - pycocotools=2.0.6
  - python=3.9.0
  - cudatoolkit=11.2
  - pytorch-gpu=1.9.0
  - scikit-learn=1.2.0
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - pip==23.0.1
  - pip:
      - brotlipy==0.7.0
      - colorama==0.4.6
      - einops==0.6.1
      - ftfy==6.1.1
      - future==0.18.3
      - inflect==5.6.0
      - jupyterlab==3.5.3
      - mkl-service==2.4.0
      - munkres==1.1.4
      - nltk==3.7
      - olefile==0.46
      - open3d==0.17.0
      - opencv-python==4.7.0.72
      - pooch==1.4.0
      - prettytable==3.7.0
      - pymongo==4.3.3
      - pyOpenSSL==22.0.0
      - PySocks==1.7.1
      - shapely==2.0.1
      - tensorboardX==2.6
      - timm==0.9.2
      - transformers==4.30.1

